export default [
    {
        "id": 1,
        "nome": "Torta com talos de acelga e champignons",
        "ingredientes": [
            "talos de acelga",
            "champignons",
            "queijo muçarela",
            "2 lâminas de massa folhada",
            "1 ovo batido",
            "azeite e temperos a gosto",
        ],
        "preparo": "Cozinhe os talos com água e um pouco de sal. Deixe-os esfriar e escorra-as bem. Lave bem os champignons e corte-os em lâminas finas. Refogue-os em um pouco de azeite. Misture os champignons com os talos de acelga cortadas e tempere com sal e pimenta a gosto. Unte com azeite uma forma para torta e abra uma lâmina de massa folhada. Coloque sobre ela o preparado de acelga e champignons. Corte o queijo em pedaços e coloque-os por cima, antes de tampar a torta com a segunda lâmina de massa. Pincele com ovo batido a massa e cozinhe a torta por 30 minutos no forno até que esteja dourada.",
        "tipo" : "refeição",
        "fonte": "GreenMe",
        "imagem": "https://i.imgur.com/MGWfk0F.jpg",
    },
    {
        "id": 2,
        "nome": "Croquetes com folhas de beterraba",
        "ingredientes": [
            "Folhas de beterraba",
            "1 ovo",
            "1 colher de queijo ralado",
            "1 colher de chá de amido de milho",
            "Sal e pimenta a gosto",
            "Farinha de rosca",
        ],
        "preparo": "Lave as folhas da betarraba e ferva-as em água. Depois, coloque-as no coador para escorrer a água. Tire toda a umidade apertando-as bem com as mãos e usando um pano de prato limpo. Quando estiverem bem secas, triture as folhas e coloque-as em um recipiente com o ovo, o sal e a pimenta. Misture bem e coloque o queijo ralado e a amido de milho. Coloque um pouco da mistura na mão e faça pequenas bolinhas. Passe-as na farinha de rosca. Frite-as ou coloque-as no forno até que fiquem bem crocantes e douradas.",
        "tipo" : "refeição",
        "fonte": "GreenMe",
        "imagem": "https://i.imgur.com/Yh8BX0t.jpg",
    },
    {
        "id": 3,
        "nome": "Salada com folhas de cenoura e frutos secos",
        "ingredientes": [
            "Folhas de cenoura",
            "4 tomates secos",
            "1 dente de alho",
            "1 punhado de amendoim ou amêndoas",
            "Sementes de gergelim",
            "Vinagre balsâmico",
            "Sal, pimenta e azeite de oliva",
        ],
        "preparo": "Hidrate os tomates em água com um pouco de vinagre balsâmico. Tire os talos grossos das folhas de cenoura e conserve apenas as folhas pequenas. Ferva as folhas de cenoura por 5 minutos. Coe-as. Refogue o alho em um pouco de azeite de oliva, adicione as folhas de cenoura, o amendoim ou as amêndoas, o gergelim, os tomates picados grossos e um pouco do vinagre. Cozinhe durante 2 minutos e sirva.",
        "tipo" : "refeição",
        "fonte": "GreenMe",
        "imagem": "https://i.imgur.com/CXdKn9p.jpg",
    },
    {
        "id": 4,
        "nome": "Tempurá de Raízes",
        "ingredientes": [
            "1 xícara de farinha de trigo integral",
            "1 + 1/4 de xícara de água",
            "1 pitada de sal",
            "1 colher de sopa de azeite",
            "Óleo de girassol para fritar",
            "1 porção de raízes (cebolinha, coentro)",
        ],
        "preparo": "Numa tigela funda, adicione a farinha de trigo integral, a água e o azeite, misturando bem para não empelotar. Adicione o sal e mexa até ficar homogêneo. Numa panela pequena, aqueça o óleo de girassol. Mergulhe as raízes na massa de tempura. Frite, um a um, no óleo quente, até dourar levemente. Forre um prato com papel toalha e retire o excesso de gordura dos tempuras.",
        "tipo" : "refeição",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/lwjl4wg.jpg",
    },
    {
        "id": 5,
        "nome": "Bolo com Calda de Casca de Maracujá",
        "ingredientes": [
            "3 xícaras de açúcar mascavo",
            "6 unidades de cravo",
            "1 canela em pau",
            "Suco de 2 maracujás",
            "250 ml de água",
            "casca de 2 maracujás",
            "2 xícaras de farinha de aveia",
            "1 xícara de farinha de arroz",
            "1 colher de sopa de fermento",
            "½ xícara de óleo de coco",
            "2 maracujás batidos com 350ml de água e ¼ de xícara de castanha de caju"
        ],
        "preparo": "Bolo: Bata no liquidificador os maracujás com a água e a castanha de caju (precisa render 1 ½ xícara, caso contrário, acrescente mais água). Numa tigela média, penere a farinha de arroz, a farinha de aveia, o açúcar, o fermente e o bicarbonato. Misture todos os ingredientes secos e acrescente o óleo de coco. Adicione o maracujá previamente batido. Pré-aqueça o forno a 190°. Unte uma forma de bolo comum, de 25 cm de diâmetro, com óleo de coco e farinha branca e despeje a massa. Leve ao forno em 190°por aproximadamente 40 minutos. Calda: Corte os maracujás e reserve o suco. Com o auxílio de um descascador, retire a parte amarela da casca e com uma colher, limpe a parte branca (pele) do maracujá. Fatie os maracujás em tiras de 1 cm. Numa panela grande, coloque os maracujás, cubra com água e leve para ferver. Ao levantar fervura, retire a água e repita este mesmo processo 3 vezes. Reserve. Bata o suco do maracujá com a água no liquidificador, despeje na panela. Adicione a canela, os cravos e o açúcar. Leve ao fogo até levantar fervura. Abaixe o fogo e deixe cozinhar por aproximadamente 15 minutos – se preciso, mexa.",
        "tipo" : "sobremesa",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/RWAQ6oo.jpg",
    },
    {
        "id": 6,
        "nome": "Suco de folha de limoeiro",
        "ingredientes": [
            "2 copos de água gelada",
            "15 a 20 folhas de limoeiro",
            "2 colheres de sopa mel ou melaço de cana",
            "1 maracujá grande",
        ],
        "preparo": "Bata todos os ingredientes no liquidificador. Coe e sirva.",
        "tipo" : "bebida",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/FdPxGGH.jpg",
    },
    {
        "id": 7,
        "nome": "Pesto de folha de cenoura",
        "ingredientes": [
            "1/3 de xicara de azeite",
            "2 xícaras de manjericão",
            "2 xícaras de ramo de cenoura",
            "2 dentes de alho",
            "100g de semente de abóbora",
            "sal a gosto",
            "3 abobrinhas",
            "2 cenouras",
            "1/4 cebola picada",
        ],
        "preparo": "Num processador, coloque o azeite, as folhas de manjericão e as folhas da ramo de cenoura, o dente de alho e por ultimo as sementes de abóbora. Processe até se tornar um pesto grosso. Acerte o sal e reserve.",
        "tipo" : "tempero",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/AZbVqg7.jpg",
    },
    {
        "id": 8,
        "nome": "Chá de casca de laranja e abacaxi",
        "ingredientes": [
            "Casca de 1 laranja",
            "Casca de 1/2 abacaxi",
            "2 canelas em pau",
            "6 cravos",
            "1 litro de água",
        ],
        "preparo": "Numa panela funda, coloque a água para ferver com todos os ingredientes. Tampe a panela e deixe ferver por cerca de 10 minutos. Apague o fogo e deixe infusionar por mais 5 minutos. Sirva ainda quente, ou se preferir, transfira para uma jarra e mantenha na geladeira, para servir gelado.",
        "tipo" : "bebida",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/gvpSMr5.jpg",
    },
    {
        "id": 9,
        "nome": "Caponata de coração de banana",
        "ingredientes": [
            "1 coração pequeno de banana",
            "1/2 xícara de vinagre ou suco de limão",
            "2 colheres de sopa de azeite extra virgem",
            "2 colheres de sopa de pimentão vermelho",
            "1/2 cebola",
            "1 dente de alho",
            "1 colher de chá de orégano",
            "2 colheres de sopa de azeitona preta",
            "sal a gosto",
            "pimenta do reino a gosto",
        ],
        "preparo": "Corte o pimentão em cubinhos, sem as sementes. Reserve. Corte a cebola em cubinhos e picar o dente de alho. Reserve. Retire as folhas grossas de fora do coração da banana, até atingir as folhas do centro, que são menos fibrosas. Reserve as folhas de fora caso queira utilizar como “cumbuquinha” para servir a caponata aos convidados.Corte o coração da banana em cubos pequenos. Numa panela com água e ¼ xícara de vinagre, adicione o coração da banana e deixe ferver por 15 minutos. Escorra e repita o processo mais uma vez. Isto cortará a “cica” presente no coração da banana, além de retirar qualquer resquício de oxidação. Escorra e reserve. Numa frigideira grande, aqueça o azeite e refogue o pimentão, em seguida, a cebola e, por último, o alho. Deixe cozinhar bem. Adicione o coração da banana escorrido. Em seguida, adicione o orégano e as azeitonas, sem caroço e fatiadas. Tempere com o sal e a pimenta. Sirva.",
        "tipo" : "refeição",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/owFGjKM.jpg",
    },
    {
        "id": 10,
        "nome": "Refogado de talo e folha de beterraba",
        "ingredientes": [
            "5 folhas de beterraba fatiadas bem finas",
            "1 dente de alho fatiado em lâminas",
            "1 colher (sopa) de óleo de coco ou ghee",
            "1 pitada de curry",
            "1 pitada de sal",
        ],
        "preparo": "Esquente o óleo de coco na frigideira, acrescente o alho e o curry e deixe dourar. Adicione as folhas e cozinhe até murchar, mas sem perder a cor (1 minuto).",
        "tipo" : "refeição",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/b92XOSq.jpg",
    },
    {
        "id": 11,
        "nome": "Macarrão de palmito com casca de banana verde",
        "ingredientes": [
            "500gr de palmito pupunha",
            "cascas de 3 bananas verdes, fatiadas",
            "2 dentes de alho picado",
            "1/4 de cebola picada",
            "1 colher (sopa) de gengibre picado",
            "4 colheres (sopa) de shoyu",
            "3 colheres (sopa) de óleo de girassol",
            "1 colher (sopa) de óleo gergelim tostado",
            "Sal marinho a gosto",
        ],
        "preparo": "Rale a pupunha num ralador largo e coloque-a em uma panela com água fervendo. Acrescente sal e um pouco de manteiga. Deixe cozinhar por 20-25 minutos. Escorra o macarrão de pupunha e reserve. Numa panela, coloque o óleo, alho, cebola, e gengibre e deixe refogar por 2 minutos em fogo médio. Adicione a casca de banana e o shoyu. Misture bem e refogue por 1 minuto. Tampe a panela e deixe cozinhar por 3- 5 minutos. Adicione o macarrão de pupunha ao refogado de casca de banana. Desligue o fogo e tempere com o óleo de gergelim tostado.",
        "tipo" : "refeição",
        "fonte": "Bela Gil",
        "imagem": "https://i.imgur.com/Tht5yJw.jpg",
    },
    {
        "id": 12,
        "nome": "Doce de casca de melancia",
        "ingredientes": [
            "1 punhado de cascas de melancia (pode usar a parte branca somente, ou com a parte verde",
            "2 colheres de sopa de cravo",
            "1 gengibre ralado",
            "suco de 1 limão",
            "2 xícaras de chá de açúcar",
            "10 sementes de cardamomo",
            "3 pedaços de canela em pau",
        ],
        "preparo": "Leve o açúcar ao fogo baixo, acrescente canela e os demais ingredientes, exceto a melancia. Mexa até formar uma calda. Em seguida, acrescente as cascas da melancia e deixe cozinhar por 15 ou 20 minutos. Espere esfriar e sirva.",
        "tipo" : "sobremesa",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/NQsCU3M.jpg",
    },
    {
        "id": 13,
        "nome": "Carne de casca de banana",
        "ingredientes": [
            "casca de 3 bananas cozidas no sal",
            "1/2 cebola picada",
            "2 dentes de alho picados",
            "azeite",
            "1 pimentão vermelho",
            "1 pimentão amarelo",
            "salsinha picada a gosto",
            "cebolinha picada a gosto",
            "3 folhas de louro",
            "fumaça líquida (opcional)",
        ],
        "preparo": "Refogue o alho, a cebola e o louro na panela com um pouco de sal e azeite. Pique as cascas da banana cozidas em cubinhos e coloque na panela com o refogado. Acrescente os pimentões, o óregano e 3 gotinhas de fumaça líquida. Deixe cozinhar por cerca de 15 minutos. Ao final, adicione a salsinha e a cebolinha. Se quiser, coloque molho de tomate. Não esqueça de retirar os louros. Sirva.",
        "tipo" : "refeição",
        "fonte": "Dayse Paparoto",
        "imagem": "https://i.imgur.com/XiI7YEz.png",
    },
    {
        "id": 14,
        "nome": "Leite de semente de melão",
        "ingredientes": [
            "sementes de um melão",
            "1 xícara de água filtrada",
        ],
        "preparo": "Limpe bem as sementes com a ajuda de uma peneira. Batas as sementes no liquidificador com a xícara de água. Em seguida, passe em um coador de de voil ou em uma peneira bem fina. Fonte de proteínas, lipídios e antioxidantes",
        "tipo" : "bebida",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/3XvrQM2.jpg",
    },
    {
        "id": 15,
        "nome": "Pipoca de semente de melancia",
        "ingredientes": [
            "sementes de uma melancia",
            "sal a gosto",
        ],
        "preparo": "Lave bem sa sementes para tirar todo o resíduo da fruta. Coloque em uma assadeira e leve ao forno a 120º por até 10 minutos para secar (não deixe torrar). Em uma frigideira, coloque as sementes e o sal. Retire quando elas começarem a pular como pipoca. Servir.",
        "tipo" : "petisco",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/1P7gzse.jpg",
    },
    {
        "id": 16,
        "nome": "Bolo de casca de banana",
        "ingredientes": [
            "4 cascas de banana",
            "4 bananas",
            "2 ovos",
            "500ml de leite",
            "2 colheres (sopa) de margarina",
            "3 + 1/2 xícaras (chá) de açúcar",
            "3 xícaras (chá) de farinha de rosca",
            "1 colher sopa de fermento em pó",
            "1 + 1/2 xícara (chá) água",
            "Suco de meio limão",
        ],
        "preparo": "Massa: Lave as bananas e descasque. Separe as cascas para fazer a massa e as bananas para a cobertura. Bata as claras em neve e guarde na geladeira. Bata no liquidificador as cascas de banana, as gemas, o leite, a margarina e o açúcar. Transfira essa mistura para uma tigela e acrescente a farinha de rosca. Mexa bem. Por último, misture delicadamente, as claras em neve e o fermento em pó. Despeje em uma fôrma redonda untada com margarina e polvilhada com farinha de rosca. Leve ao forno médio, preaquecido, por aproximadamente 40 minutos. Cobertura: Derreta o açúcar em uma panela e junte a água, fazendo um caramelo. Acrescente as bananas cortadas em rodelas e o suco de limão. Cozinhe até as bananas amolecerem. Cubra o bolo ainda quente com essa cobertura.",
        "tipo" : "sobremesa",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/PYnlVDc.jpg",
    },
    {
        "id": 17,
        "nome": "Petisco de semente de abóbora",
        "ingredientes": [
            "sementes de uma abóbora",
            "sal",
            "chimi churry ou chilli",
        ],
        "preparo": "Retire as sementes da abóbora e lave-as bem. Seque-as com um guardanapo. Coloque as sementes em uma assadeira, jogue chilli/chimi churry e uma pitadinha de sal por cima. Leve ao forno pré-aquecido (180º) por 5 a 10 minutos ou até que fiquem levemente torradas",
        "tipo" : "petisco",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/rxzKALd.jpg",
    },
    {
        "id": 18,
        "nome": "Cascas de laranja cristalizadas",
        "ingredientes": [
            "1 kg de cascas de laranja cortadas em finas tirinhas",
            "200g de açúcar",
        ],
        "preparo": "Coloque as tirinahs na água e deixe ferver por 5 minutos. A água da fervura precisa ser trocada pelo menos 5 vezes, pois a casca da laranja é muito ácida. Depois disso, escorra a água. Leve ao fogo e mexa por uns 10 minutos. Assim que as tiras começarem a soltar umas das outras, tire-as do fogo e mexa a panela por mais um minuto. Depois, espalhe as tiras num tabuleiro e deixe esfriar.",
        "tipo" : "petisco",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/R8NMjuD.png",
    },
    {
        "id": 19,
        "nome": "Sementes de mamão como pimenta",
        "ingredientes": [
            "sementes de mamão",
        ],
        "preparo": "Lave bem as sementes e leve ao forno baixo por alguns minutos para desidratar. Pode ser usada no lugar da sementa preta nos temperos. É menos picante e seu sabor lembra uma mistura dapimenta com mostarda",
        "tipo" : "tempero",
        "fonte": "Edson Leite",
        "imagem": "https://i.imgur.com/pDRTfhS.jpg",
    },
    {
        "id": 20,
        "nome": "Caldo verde com taioba",
        "ingredientes": [
            "2 kg de batata com casca",
            "2 dentes de alho picados",
            "1/2 cebola picada",
            "2 colheres (sopa) azeite",
            "pimenta-do-reino e sal a gosto",
            "2 linguiças calabresas cortadas em cubos pequenos",
            "1 maço de taioba",
            "1 punhado de salsa picada",
        ],
        "preparo": "Lave bem as folhas da taioba e coloque-as num liquidificador, acrescente 3 xícaras de água e bata ate obter um suco verde de taioba. Ligue o fogo da panela, doure o alho com o azeite ou óleo, em seguida coloque as batatas e por último acrescente o suco de taioba. Complete com água até cobrir as batatas e deixe cozinhar até que a batata fique macia. Acrescente sal e pimenta do reino a gosto. Quando as batatas estiverem cozidas bata tudo num liquidificador até obter um caldo homogêneo.",
        "tipo" : "refeição",
        "fonte": "Jornada Vegana",
        "imagem": "https://i.imgur.com/BFrUhzi.jpg",
    },
    {
        "id": 21,
        "nome": "Bolo de casca de abóbora",
        "ingredientes": [
            "1 xícara e meia de farinha de trigo",
            "3 quartos de xícara de amido de milho",
            "2 xícaras de açúcar, mais 4 colheres de sopa para a cobertura",
            "3 ovos",
            "1 colher de sopa de fermento em pó",
            "4 colheres de sopa de leite",
            "4 colheres de sopa de chocolate em pó",
            "1 punhado de salsa picada",
        ],
        "preparo": "Bata no liquidificador as cascas, ovos e óleo. À parte, peneire em uma tigela a farinha, amido de milho, açúcar e fermento. Junte a mistura do liquidificador e misture muito bem. Unte uma assadeira média com margarina e farinha, coloque a mistura e leve para assar em forno médio.",
        "tipo" : "sobremesa",
        "fonte": "eCycle",
        "imagem": "https://i.imgur.com/JVuIO10.jpg",
    },
    {
        "id": 22,
        "nome": "Doce de Casca de Maracujá",
        "ingredientes": [
            "6 cascas de maracujás",
            "2 xícaras de açúcar",
            "3 xícaras de água",
        ],
        "preparo": "Deixe toda a parte branca e dura da casca imersa em água, de molho de um dia para o outro. Depois, escorra, coloque em uma panela com 2 xícaras de açúcar e 3 xícaras de água. Deixe apurar. E, se quiser, acrescente canela.",
        "tipo" : "sobremesa",
        "fonte": "eCycle",
        "imagem": "https://i.imgur.com/JgHAq1D.jpg",
    },
    {
        "id": 23,
        "nome": "Macarrão de talos",
        "ingredientes": [
            "300 gramas de macarrão de sua preferência",
            "4 dentes de alho",
            "3 colheres de sopa de azeite",
            "1 xícara de chá de ramos de cenouras",
            "3 xícaras de chá de talos (brócolis, beterraba, couve)",
            "sal a gosto",
        ],
        "preparo": "Em uma panela, doure os dentes de alho inteiros no azeite. Acrescente os talos, os ramos e refogue. Junte o macarrão cozido al dente e verifique o sal.",
        "tipo" : "refeição",
        "fonte": "eCycle",
        "imagem": "https://i.imgur.com/xW6InMQ.jpg",
    },
    {
        "id": 24,
        "nome": "Farofa de Casca de Melão",
        "ingredientes": [
            "2 xícaras de chá de casca de melão picada",
            "4 colheres de sopa de azeite",
            "4 colheres de sopa de cebola picada",
            "2 dentes de alho picado",
            "2 xícaras de chá de talos picados",
            "2 xícaras de chá de suco de casca de abacaxi",
            "2 xícaras de chá de tomate picado",
            "4 xícaras de chá de farinha de mandioca",
            "sal a gosto"
        ],
        "preparo": "Ferva a casca de melão até ficar macia. Escorra e reserve. Aqueça o azeite e doure a cebola e o alho, acrescente os talos, a casca do melão e refogue. Junte o suco e o sal. Deixe levantar fervura. Por fim, acrescente o tomate picado e a farinha de mandioca. Mexa bem e sirva quente ou frio. No caso do suco da casca do abacaxi, as cascas devem ser cozidas por 15 à 20 minutos.",
        "tipo" : "refeição",
        "fonte": "eCycle",
        "imagem": "https://i.imgur.com/RkyvoSh.png",
    },
    {
        "id": 25,
        "nome": "Brigadeiro de Casca de Banana",
        "ingredientes": [
            "3 cascas de bananas em tiras",
            "1 xícara de açúcar",
            "2 colheres de sopa de margarina",
            "4 colheres de farinha de trigo",
            "1 xícara de leite morno",
            "1 xícara de leite em pó",
            "2 colheres de sopa de achocolatado",
            "1 xícara de chocolate granulado",
        ],
        "preparo": "Em uma panela coloque as cascas de banana, a água e o açúcar. Cozinhe até ficar pastoso. Acrescente os demais ingredientes, exceto o chocolate granulado, e mexa até desprender do fundo da panela. Coloque num prato e deixe esfriar. Faça bolinhas e passe-as no chocolate granulado.",
        "tipo" : "sobremesa",
        "fonte": "Mais Caminhos",
        "imagem": "https://i.imgur.com/d2w3dQ8.jpg",
    },
    {
        "id": 26,
        "nome": "Suco de Casca de Abacaxi e Cidreira",
        "ingredientes": [
            "Casca de 1 abacaxi",
            "1 xícara de chá de capim cidreira",
            "1 litro de água",
        ],
        "preparo": "Bata no liquidificador as cascas de abacaxi, o capim cidreira e a água. Coe. Adoce se for necessário e sirva.",
        "tipo" : "bebida",
        "fonte": "Guia da Semana",
        "imagem": "https://i.imgur.com/S8e7DlE.jpg",
    },
    {
        "id": 27,
        "nome": "Arroz cremoso de casca de abóbora",
        "ingredientes": [
            "1 cebola picada",
            "Cascas de 1 abóbora",
            "1 xícara de água",
            "3 xícaras de arroz cozido",
            "1 xícara de abóbora picada",
            "1/2 caixinha de creme de leite",
            "1/2 copo de requeijão",
            "sal a gosto"
        ],
        "preparo": "Refogue a cebola em uma panela. Adicione a casca de abóbora ralada e a água e deixe cozinhar por 15 minutos. Acrescente a abóbora e refogue bem. Aos poucos, coloque o arroz já cozido, alternando com o creme de leite e o requeijão. Por último, tempere com sal a gosto.",
        "tipo" : "refeição",
        "fonte": "Guia da Semana",
        "imagem": "https://i.imgur.com/UtB2ha5.jpg",
    },
    {
        "id": 28,
        "nome": "Creme de Folha de Couve-flor",
        "ingredientes": [
            "1 cebola picada",
            "4 xícaras de folhas de couve-flor",
            "1 colher de farinha de trigo",
            "1 xícara de leite",
            "1 colher de queijo ralado",
            "1 xícara de água",
        ],
        "preparo": "Refogue e acrescente as folhas de couve-flor bem lavadas e picadas. Em uma tigela, incorpore delicadamente a farinha ao leite e junte o queijo ralado e a água. Adicione ao refogado e deixe o creme encorpar. Tempere com sal a gosto. Sirva quente.",
        "tipo" : "refeição",
        "fonte": "Guia da Semana",
        "imagem": "https://i.imgur.com/1K0X1ey.jpg",
    },
    {
        "id": 29,
        "nome": "Geleia de casca de mamão",
        "ingredientes": [
            "Cascas de 2 mamões",
            "1 xícara de água",
            "1 e 1/2 xícara de açúcar",
            "1 pau de canela",
            "2 cravos",
        ],
        "preparo": "Bata as cascas com a água no liquidificador. Leve ao fogo com o açúcar, a canela e os cravos, cozinhando em fogo brando e mexendo sempre. Estará pronto quando tiver o ponto de geléia.",
        "tipo" : "sobremesa",
        "fonte": "Guia da Semana",
        "imagem": "https://i.imgur.com/wtxUbp5.jpg",
    },
    {
        "id": 30,
        "nome": "Doce de casca de banana",
        "ingredientes": [
            "Casca de 6 bananas nanicas",
            "2 xícaras de açúcar",
            "1 xícara de água",
            "1 colher (sopa) de suco de limão",
            "4 cravos",
            "2 pedaços de canela em pau",
        ],
        "preparo": "Numa panela média, junte as cascas de banana e cubra com água. Leve ao fogo médio e deixe ferver por cinco minutos ou até ficarem macias. Escorra-as e corte-as em pedaços. Bata no liquidificador até obter um purê. Coloque novamente na panela e junte os demais ingredientes. Leve ao fogo médio, com a panela semitampada, mexendo às vezes, por cerca de 35 minutos ou até a mistura soltar do fundo. Retire do fogo e deixe esfriar.",
        "tipo" : "sobremesa",
        "fonte": "Guia da Semana",
        "imagem": "https://i.imgur.com/duZICyu.jpg",
    },
]